### ISSUE TITLE
Stupid Crash

### ISSUE THREAD

**Issue by alexandermburke** [papertazer/Trinia-Mod-BETA#2]
[21:18:10] [main/INFO] [GradleStart]: Extra: []
[21:18:10] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --accessToken, {REDACTED}, --assetIndex, 1.8, --assetsDir, C:/Users/Lori Burke/.gradle/caches/minecraft/assets, --version, 1.8, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[21:18:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:18:11] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:18:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[21:18:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:18:11] [main/INFO] [FML]: Forge Mod Loader version 8.99.124.1450 for Minecraft 1.8 loading
[21:18:11] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_75, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre7
[21:18:11] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[21:18:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[21:18:11] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[21:18:11] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[21:18:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:18:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:18:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[21:18:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:18:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:18:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:18:12] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[21:18:16] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[21:18:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:18:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:18:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[21:18:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:18:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:18:18] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:18:22] [Client thread/INFO]: Setting user: Player892
[21:18:28] [Client thread/INFO]: LWJGL Version: 2.9.1
[21:18:30] [Client thread/INFO] [STDOUT]: [net.minecraftforge.fml.client.SplashProgress:start:235]: ---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 11/15/15 9:18 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 10 (amd64) version 6.3
    Java Version: 1.7.0_75, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 148728056 bytes (141 MB) / 250085376 bytes (238 MB) up to 1169162240 bytes (1115 MB)
    JVM Flags: 0 total; 
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4252' Renderer: 'EVGA GeForce GTX 980'
[21:18:31] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[21:18:31] [Client thread/INFO] [FML]: MinecraftForge v11.14.3.1450 Initialized
[21:18:31] [Client thread/INFO] [FML]: Replaced 204 ore recipies
[21:18:31] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[21:18:32] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[21:18:32] [Client thread/INFO] [FML]: Searching C:\Users\Lori Burke\Desktop\Trinia Mod\mods for mods
[21:18:39] [Client thread/INFO] [FML]: Forge Mod Loader has identified 4 mods to load
[21:18:39] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, trinia] at CLIENT
[21:18:39] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, trinia] at SERVER
[21:18:41] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Trinia Mod
[21:18:42] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[21:18:42] [Client thread/INFO] [FML]: Found 384 ObjectHolder annotations
[21:18:42] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[21:18:42] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[21:18:42] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[21:18:44] [Client thread/WARN] [FML]: ****************************************
[21:18:44] [Client thread/WARN] [FML]: \* The object com.trinia.blocks.BlockTrinia@1ea6281d has been registered twice for the same name trinia:copperOre.
[21:18:44] [Client thread/WARN] [FML]: \*  at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:429)
[21:18:44] [Client thread/WARN] [FML]: \*  at net.minecraftforge.fml.common.registry.GameData.registerBlock(GameData.java:827)
[21:18:44] [Client thread/WARN] [FML]: \*  at net.minecraftforge.fml.common.registry.GameData.registerBlock(GameData.java:802)
[21:18:44] [Client thread/WARN] [FML]: \*  at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:220)
[21:18:44] [Client thread/WARN] [FML]: \*  at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:188)
[21:18:44] [Client thread/WARN] [FML]: \*  at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:177)...
[21:18:44] [Client thread/WARN] [FML]: ****************************************
[21:18:44] [Client thread/ERROR] [FML]: Caught an exception during block registration
java.lang.IllegalStateException: Can't free registry slot 198 occupied by net.minecraft.item.ItemBlock@5bc86638
    at net.minecraftforge.fml.common.registry.GameData.freeSlot(GameData.java:876) ~[GameData.class:?]
    at net.minecraftforge.fml.common.registry.GameData.registerItem(GameData.java:776) ~[GameData.class:?]
    at net.minecraftforge.fml.common.registry.GameData.registerItem(GameData.java:745) ~[GameData.class:?]
    at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:223) [GameRegistry.class:?]
    at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:188) [GameRegistry.class:?]
    at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:177) [GameRegistry.class:?]
    at com.trinia.blocks.TriniaBlocks.register(TriniaBlocks.java:113) [TriniaBlocks.class:?]
    at com.trinia.blocks.TriniaBlocks.load(TriniaBlocks.java:21) [TriniaBlocks.class:?]
    at com.trinia.TriniaMod.preInit(TriniaMod.java:88) [TriniaMod.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537) [FMLModContainer.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:550) [Loader.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:248) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:446) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:356) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:117) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
    at GradleStart.main(Unknown Source) [start/:?]
[21:18:44] [Client thread/INFO] [FML]: Applying holder lookups
[21:18:44] [Client thread/INFO] [FML]: Holder lookups applied
[21:18:44] [Client thread/INFO] [FML]: Injecting itemstacks
[21:18:44] [Client thread/INFO] [FML]: Itemstack injection complete
[21:18:44] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[21:18:44] [Client thread/ERROR] [FML]: 
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forgeSrc-1.8-11.14.3.1450.jar) 
    UCH Forge{11.14.3.1450} [Minecraft Forge](forgeSrc-1.8-11.14.3.1450.jar) 
    UCE trinia{2.0} [Trinia Mod](bin) 
[21:18:44] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[21:18:44] [Client thread/ERROR] [FML]: Caught exception from trinia
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalStateException: Can't free registry slot 198 occupied by net.minecraft.item.ItemBlock@5bc86638

```
at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:231) ~[forgeSrc-1.8-11.14.3.1450.jar:?]
at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:188) ~[forgeSrc-1.8-11.14.3.1450.jar:?]
at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:177) ~[forgeSrc-1.8-11.14.3.1450.jar:?]
at com.trinia.blocks.TriniaBlocks.register(TriniaBlocks.java:113) ~[bin/:?]
at com.trinia.blocks.TriniaBlocks.load(TriniaBlocks.java:21) ~[bin/:?]
at com.trinia.TriniaMod.preInit(TriniaMod.java:88) ~[bin/:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537) ~[forgeSrc-1.8-11.14.3.1450.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forgeSrc-1.8-11.14.3.1450.jar:?]
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forgeSrc-1.8-11.14.3.1450.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:550) [Loader.class:?]
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:248) [FMLClientHandler.class:?]
at net.minecraft.client.Minecraft.startGame(Minecraft.java:446) [Minecraft.class:?]
at net.minecraft.client.Minecraft.run(Minecraft.java:356) [Minecraft.class:?]
at net.minecraft.client.main.Main.main(Main.java:117) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
at GradleStart.main(Unknown Source) [start/:?]
```

Caused by: java.lang.IllegalStateException: Can't free registry slot 198 occupied by net.minecraft.item.ItemBlock@5bc86638
    at net.minecraftforge.fml.common.registry.GameData.freeSlot(GameData.java:876) ~[forgeSrc-1.8-11.14.3.1450.jar:?]
    at net.minecraftforge.fml.common.registry.GameData.registerItem(GameData.java:776) ~[forgeSrc-1.8-11.14.3.1450.jar:?]
    at net.minecraftforge.fml.common.registry.GameData.registerItem(GameData.java:745) ~[forgeSrc-1.8-11.14.3.1450.jar:?]
    at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:223) ~[forgeSrc-1.8-11.14.3.1450.jar:?]
    ... 44 more
[21:18:44] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:663]: ---- Minecraft Crash Report ----
// You're mean.

Time: 11/15/15 9:18 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalStateException: Can't free registry slot 198 occupied by net.minecraft.item.ItemBlock@5bc86638
    at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:231)
    at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:188)
    at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:177)
    at com.trinia.blocks.TriniaBlocks.register(TriniaBlocks.java:113)
    at com.trinia.blocks.TriniaBlocks.load(TriniaBlocks.java:21)
    at com.trinia.TriniaMod.preInit(TriniaMod.java:88)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:550)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:248)
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:446)
    at net.minecraft.client.Minecraft.run(Minecraft.java:356)
    at net.minecraft.client.main.Main.main(Main.java:117)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
    at GradleStart.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Can't free registry slot 198 occupied by net.minecraft.item.ItemBlock@5bc86638
    at net.minecraftforge.fml.common.registry.GameData.freeSlot(GameData.java:876)
    at net.minecraftforge.fml.common.registry.GameData.registerItem(GameData.java:776)
    at net.minecraftforge.fml.common.registry.GameData.registerItem(GameData.java:745)
    at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:223)
    ... 44 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 10 (amd64) version 6.3
    Java Version: 1.7.0_75, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 118545824 bytes (113 MB) / 362283008 bytes (345 MB) up to 1169162240 bytes (1115 MB)
    JVM Flags: 0 total; 
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1450 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forgeSrc-1.8-11.14.3.1450.jar) 
    UCH Forge{11.14.3.1450} [Minecraft Forge](forgeSrc-1.8-11.14.3.1450.jar) 
    UCE trinia{2.0} [Trinia Mod](bin) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4252' Renderer: EVGA GeForce GTX 980'
[21:18:44] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:663]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Alex\Desktop\Trinia Mod.\crash-reports\crash-2015-11-15_21.18.44-client.txt

**Comment by DShillington** [comment]
ffs i fixed that same crash like 6 times

**Comment by DShillington** [comment]
Fixed. 

PreInit method was inside the common proxy and the main class. Took it out of the common proxy.
